# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  shell: bash
  variables:
    DOCKERHUB_ORGANIZATION: "protofire"
    DOCKERHUB_REPO_NAME: "cid-checker"
    APP_VERSION: "0.1.38-mainnet"
    DOCKER_BUILDX_VERSION: "v0.10.4"
  secrets-manager:
    DOCKERHUB_USERNAME: "filecoin-mainnet-apn1-glif-dockerhub-glifio:username"
    DOCKERHUB_PASS: "filecoin-mainnet-apn1-glif-dockerhub-glifio:password"

phases:
  install:
    commands:
      - curl -JLO https://github.com/docker/buildx/releases/download/${DOCKER_BUILDX_VERSION}/buildx-${DOCKER_BUILDX_VERSION}.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-${DOCKER_BUILDX_VERSION}.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - docker buildx create --use --name cid_checker
      - docker buildx inspect --bootstrap

  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS

  build:
    commands:
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-s3-sort-caching-multi -f Dockerfile.s3-sort-caching .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-backend-multi -f Dockerfile.backend .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-watcher-multi -f Dockerfile.watcher .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-frontend-multi -f Dockerfile.frontend --build-arg REACT_APP_FILECOIN_CID_CHECKER_API=/api .
