# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  shell: bash
  variables:
    PROJECT: "filecoin"
    SUB_ENV: "glif"
    SHORT_REGION: "apn1"
    ENVIRONMENT: "dev"
    HELM_VERSION: "v3.1.0"
    APP_VERSION: "0.1.38"
    NETWORK: "mainnet"
    ARCH: "amd64"
  secrets-manager:
    AWS_ACCESS_KEY_ID: "filecoin-dev-apn1-glif-codebuild-user:AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "filecoin-dev-apn1-glif-codebuild-user:AWS_SECRET_ACCESS_KEY"

phases:
  install:
    commands:
      - wget https://get.helm.sh/helm-${HELM_VERSION}-linux-${ARCH}.tar.gz
      - tar -xzvf helm-${HELM_VERSION}-linux-${ARCH}.tar.gz
      - chmod +x ./linux-${ARCH}/helm
      - mv ./linux-${ARCH}/helm /usr/bin/helm

  pre_build:
    commands:
      - aws eks --region $AWS_REGION update-kubeconfig --name $PROJECT-$ENVIRONMENT-$SHORT_REGION-$SUB_ENV-eks

  build:
    commands:
      - echo Building docker images
      - cd helm
      - sed -i "s/0.0.0/${APP_VERSION}/g" Chart.yaml
      - helm lint
      - helm template cid-checker-$NETWORK . -f env-values/$NETWORK.yaml
      - helm upgrade --install cid-checker-$NETWORK . -f env-values/$NETWORK.yaml
