# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  shell: bash
  variables:
    HELM_VERSION: 'v3.1.0'
    ARCH: 'amd64'

phases:
  install:
    commands:
      - echo Environment Variables
      - printenv
      - echo Installing Helm
      - wget https://get.helm.sh/helm-${HELM_VERSION}-linux-${ARCH}.tar.gz
      - tar -xzvf helm-${HELM_VERSION}-linux-${ARCH}.tar.gz
      - chmod +x ./linux-${ARCH}/helm
      - mv ./linux-${ARCH}/helm /usr/bin/helm

  pre_build:
    commands:
      - echo Build STARTED
      #
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-s3-sort-caching-multi -f Dockerfile.s3-sort-caching .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-backend-multi -f Dockerfile.backend .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-watcher-multi -f Dockerfile.watcher .
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:$APP_VERSION-frontend-multi -f Dockerfile.frontend --build-arg REACT_APP_FILECOIN_CID_CHECKER_API=/api .
      #
      - cd helm
      - helm lint
  build:
    commands:
      - echo Image built