apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "CID.fullname" . }}-backend
  labels:
    {{- include "CID.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "CID.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "CID.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.services.backend.image.repository }}:{{ .Chart.AppVersion }}-backend"
          imagePullPolicy: {{ .Values.services.backend.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "yarn run migrate:prod"]
          ports:
            - name: api
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs
              port: api
          readinessProbe:
            httpGet:
              path: /docs
              port: api
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: "3000"
            - name: APP_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: CID_LOTUS_RPCURL
              value: "{{ .Values.lotusURL }}"
            - name: CID_DB_CONNECTIONSTRING
              value: "mongodb://{{ include "CID.fullname" . }}-mongo-service:27017"
            - name: CID_DB_NAME
              value: "{{ .Values.services.mongo.dbName }}"
      {{- range $key, $value := .Values.services.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
