apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "CID.fullname" . }}-frontend
  labels:
    {{- include "CID.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "CID.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "CID.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.services.frontend.image.repository }}:{{ .Chart.AppVersion }}-frontend"
          imagePullPolicy: {{ .Values.services.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: REACT_APP_REPOSITORY_URL
              value: "https://github.com/glifio/cid-checker"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
