apiVersion: v1
kind: Service
metadata:
  name: {{ include "CID.fullname" . }}-backend-service
  labels:
    {{- include "CID.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: api
      protocol: TCP
      name: backend 
  selector:
    {{- include "CID.selectorLabels" . | nindent 4 }}
    component: backend
