apiVersion: v1
kind: Service
metadata:
  name: {{ include "CID.fullname" . }}-mongo-service
  labels:
    {{- include "CID.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: db
      protocol: TCP
      name: db 
  selector:
    {{- include "CID.selectorLabels" . | nindent 4 }}
    component: mongo
